package web

import (
	"fmt"
	"net/http"
	"os"
	"runtime"
	"strings"
)

// nodeBootstrap serves a one-shot shell installer for a newly enrolled node.
func (h *Handler) nodeBootstrap(w http.ResponseWriter, r *http.Request) {
	if h.Nodes == nil {
		http.Error(w, "nodes not available", http.StatusInternalServerError)
		return
	}
	token := strings.TrimSpace(r.URL.Query().Get("token"))
	if token == "" {
		http.Error(w, "missing token", http.StatusBadRequest)
		return
	}
	if _, ok := h.Nodes.Authenticate(token); !ok {
		http.Error(w, "invalid token", http.StatusUnauthorized)
		return
	}
	panel := publicBaseFromRequest(r)
	script := nodeBootstrapScript(panel, token)
	w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("Content-Disposition", `inline; filename="craftpanel-node.sh"`)
	_, _ = w.Write([]byte(script))
}

// nodeBinary serves this panel's own executable for same-OS/arch node installs.
func (h *Handler) nodeBinary(w http.ResponseWriter, r *http.Request) {
	if h.Nodes == nil {
		http.Error(w, "nodes not available", http.StatusInternalServerError)
		return
	}
	token := strings.TrimSpace(r.URL.Query().Get("token"))
	if token == "" || !strings.HasPrefix(token, "node_") {
		http.Error(w, "missing token", http.StatusUnauthorized)
		return
	}
	if _, ok := h.Nodes.Authenticate(token); !ok {
		http.Error(w, "invalid token", http.StatusUnauthorized)
		return
	}
	exe, err := os.Executable()
	if err != nil {
		http.Error(w, "binary unavailable", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="craftpanel-%s-%s"`, runtime.GOOS, runtime.GOARCH))
	w.Header().Set("X-Craftpanel-OS", runtime.GOOS)
	w.Header().Set("X-Craftpanel-Arch", runtime.GOARCH)
	http.ServeFile(w, r, exe)
}

func nodeBootstrapScript(panelURL, token string) string {
	panelURL = strings.TrimRight(panelURL, "/")
	const tmpl = `#!/usr/bin/env bash
# ComputeBox Craftpanel — remote node bootstrap (generated by the panel)
set -euo pipefail

PANEL_URL='__PANEL_URL__'
NODE_TOKEN='__NODE_TOKEN__'
REPO="${CRAFTPANEL_REPO:-computenord/craftpanel}"
DATA_DIR="${CRAFTPANEL_NODE_DATA:-/var/lib/craftpanel-node}"
BIN="$DATA_DIR/bin/craftpanel"
BIN_LINK=/usr/local/bin/craftpanel
UNIT=/etc/systemd/system/craftpanel-node.service
SERVICE_USER=craftpanel

say()  { printf '\033[1;34m[craftpanel-node]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[craftpanel-node]\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || fail "Run as root: curl -fsSL '…/bootstrap?token=…' | sudo bash"
command -v systemctl >/dev/null 2>&1 || fail "systemd is required"
command -v curl >/dev/null 2>&1 || fail "curl is required"

case "$(uname -s)" in
  Linux) ;;
  *) fail "Only Linux nodes are supported (got $(uname -s))" ;;
esac
case "$(uname -m)" in
  x86_64|amd64)  ARCH=amd64 ;;
  aarch64|arm64) ARCH=arm64 ;;
  *) fail "Unsupported architecture: $(uname -m)" ;;
esac

say "Installing Craftpanel node agent → $PANEL_URL"
say "Data directory: $DATA_DIR"

TMP=$(mktemp)
HDR=$(mktemp)
trap 'rm -f "$TMP" "$HDR"' EXIT

DOWNLOAD_OK=0
if curl -fsSL -D "$HDR" -o "$TMP" "$PANEL_URL/api/nodes/binary?token=$NODE_TOKEN"; then
  HDR_OS=$(grep -i '^X-Craftpanel-OS:' "$HDR" | awk '{print tolower($2)}' | tr -d '\r' || true)
  HDR_ARCH=$(grep -i '^X-Craftpanel-Arch:' "$HDR" | awk '{print tolower($2)}' | tr -d '\r' || true)
  if [ "$HDR_OS" = "linux" ] && [ "$HDR_ARCH" = "$ARCH" ]; then
    DOWNLOAD_OK=1
    say "Downloaded binary from panel"
  else
    say "Panel binary is $HDR_OS/$HDR_ARCH — falling back to GitHub for linux/$ARCH"
  fi
fi
if [ "$DOWNLOAD_OK" -ne 1 ]; then
  URL="https://github.com/$REPO/releases/latest/download/craftpanel-linux-$ARCH"
  say "Downloading craftpanel-linux-$ARCH from GitHub"
  curl -fSL --progress-bar -o "$TMP" "$URL" || fail "Download failed: $URL"
fi
chmod 755 "$TMP"

if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  say "Creating system user $SERVICE_USER"
  useradd --system --home-dir "$DATA_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"
fi

mkdir -p "$DATA_DIR/bin"
install -m 755 -o "$SERVICE_USER" -g "$SERVICE_USER" "$TMP" "$BIN"
ln -sfn "$BIN" "$BIN_LINK"

# Advertised URL the panel uses to reach this node's control API.
# Override with CRAFTPANEL_NODE_URL=https://node.example.com:8421 when behind NAT.
NODE_API_PORT="${CRAFTPANEL_NODE_API_PORT:-8421}"
NODE_LISTEN=":${NODE_API_PORT}"
if [ -n "${CRAFTPANEL_NODE_URL:-}" ]; then
  NODE_API_URL="$CRAFTPANEL_NODE_URL"
else
  NODE_IP=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}' || true)
  if [ -z "$NODE_IP" ]; then
    NODE_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
  fi
  if [ -z "$NODE_IP" ]; then
    NODE_IP=127.0.0.1
  fi
  NODE_API_URL="http://${NODE_IP}:${NODE_API_PORT}"
fi

umask 077
cat > "$DATA_DIR/node-agent.json" <<EOF
{
  "panelUrl": "$PANEL_URL",
  "token": "$NODE_TOKEN",
  "listen": "$NODE_LISTEN",
  "apiUrl": "$NODE_API_URL"
}
EOF
chown -R "$SERVICE_USER:$SERVICE_USER" "$DATA_DIR"
chmod 750 "$DATA_DIR"
chmod 600 "$DATA_DIR/node-agent.json"

systemctl disable --now craftpanel-node 2>/dev/null || true

say "Writing systemd service"
cat > "$UNIT" <<EOF
[Unit]
Description=ComputeBox Craftpanel Node Agent
Documentation=https://github.com/$REPO
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
ExecStart=$BIN node -data $DATA_DIR
Restart=always
RestartSec=3
KillMode=process
TimeoutStopSec=90
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$DATA_DIR
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now craftpanel-node

if ! command -v java >/dev/null 2>&1; then
  say "NOTE: Java not found — install a JRE before creating Minecraft servers on this node."
fi

say ""
say "Done. This host is now a Craftpanel node."
say "  Control API: $NODE_API_URL (panel must reach this)"
say "  systemctl status craftpanel-node"
say "  journalctl -u craftpanel-node -f"
say "If the panel cannot reach the node, set CRAFTPANEL_NODE_URL and re-run bootstrap,"
say "or edit $DATA_DIR/node-agent.json (apiUrl) and restart craftpanel-node."
`
	out := strings.ReplaceAll(tmpl, "__PANEL_URL__", shellSingleQuote(panelURL))
	out = strings.ReplaceAll(out, "__NODE_TOKEN__", shellSingleQuote(token))
	// shellSingleQuote already wraps; we used placeholders inside single quotes
	// so strip the outer quotes from the helper and embed raw escaped values.
	return out
}

func shellSingleQuote(s string) string {
	// Value for embedding inside bash single quotes: 'foo'\''bar'
	return strings.ReplaceAll(s, "'", `'\''`)
}

// JoinCommand is the one-liner shown in the UI after enroll.
func JoinCommand(panelURL, token string) string {
	panelURL = strings.TrimRight(panelURL, "/")
	return fmt.Sprintf("curl -fsSL '%s/api/nodes/bootstrap?token=%s' | sudo bash", panelURL, token)
}
