package mc

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/computenord/craftpanel/internal/fsutil"
)

// A Velocity proxy and its Paper backends are wired up here: the panel owns
// the [servers] block in velocity.toml (between marker comments) and pushes
// the forwarding secret into each backend's paper-global.yml.

var ErrNotVelocity = errors.New("this server is not a velocity proxy")

const (
	velocityConfig  = "velocity.toml"
	forwardSecret   = "forwarding.secret"
	serversBlockTop = "# craftpanel:servers:start"
	serversBlockEnd = "# craftpanel:servers:end"
)

// writeVelocityConfig creates the initial proxy configuration at server
// creation time.
func writeVelocityConfig(dataDir, name string, port int) error {
	secret := make([]byte, 12)
	if _, err := rand.Read(secret); err != nil {
		return err
	}
	if err := fsutil.WriteFileAtomic(filepath.Join(dataDir, forwardSecret), []byte(hex.EncodeToString(secret)), 0o600); err != nil {
		return err
	}
	toml := fmt.Sprintf(`# Generated by ComputeBox Craftpanel
config-version = "2.7"
bind = "0.0.0.0:%d"
motd = "%s"
show-max-players = 500
online-mode = true
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"

%s
[servers]
try = []
%s

[advanced]
`, port, sanitizeMOTD(name), serversBlockTop, serversBlockEnd)
	return fsutil.WriteFileAtomic(filepath.Join(dataDir, velocityConfig), []byte(toml), 0o644)
}

type NetworkBackend struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Port   int    `json:"port"`
	Linked bool   `json:"linked"`
}

type NetworkInfo struct {
	Backends []NetworkBackend `json:"backends"`
}

// Network lists the Paper servers on this host and whether they are wired to
// the given Velocity proxy.
func (m *Manager) Network(id string) (NetworkInfo, error) {
	srv, err := m.get(id)
	if err != nil {
		return NetworkInfo{}, err
	}
	if srv.meta.Type != TypeVelocity {
		return NetworkInfo{}, ErrNotVelocity
	}
	linked := map[string]bool{}
	srv.mu.Lock()
	for _, l := range srv.meta.NetworkServers {
		linked[l] = true
	}
	srv.mu.Unlock()

	info := NetworkInfo{Backends: []NetworkBackend{}}
	for _, v := range m.List() {
		// Modern forwarding needs Paper; Vanilla and Bedrock cannot join a
		// Velocity network this way.
		if v.Type != TypePaper {
			continue
		}
		info.Backends = append(info.Backends, NetworkBackend{
			ID: v.ID, Name: v.Name, Port: v.Port, Linked: linked[v.ID],
		})
	}
	sort.Slice(info.Backends, func(i, j int) bool { return info.Backends[i].ID < info.Backends[j].ID })
	return info, nil
}

// SetNetwork wires the chosen Paper servers to the proxy: velocity.toml gets
// the server list, every chosen backend gets the forwarding secret and
// online-mode=false. Returns human readable warnings (restart reminders).
func (m *Manager) SetNetwork(id string, serverIDs []string) ([]string, error) {
	srv, err := m.get(id)
	if err != nil {
		return nil, err
	}
	if srv.meta.Type != TypeVelocity {
		return nil, ErrNotVelocity
	}
	secretBytes, err := os.ReadFile(filepath.Join(srv.DataDir(), forwardSecret))
	if err != nil {
		return nil, fmt.Errorf("read forwarding secret: %w", err)
	}
	secret := strings.TrimSpace(string(secretBytes))

	// Validate the chosen backends first.
	type backend struct {
		id   string
		port int
		srv  *Server
	}
	backends := []backend{}
	seen := map[string]bool{}
	for _, sid := range serverIDs {
		if seen[sid] || sid == id {
			continue
		}
		seen[sid] = true
		b, err := m.get(sid)
		if err != nil {
			return nil, fmt.Errorf("server %q not found", sid)
		}
		b.mu.Lock()
		typ, port := b.meta.Type, b.meta.Port
		b.mu.Unlock()
		if typ != TypePaper {
			return nil, fmt.Errorf("server %q is not a paper server", sid)
		}
		backends = append(backends, backend{id: sid, port: port, srv: b})
	}

	// Rebuild the managed [servers] block in velocity.toml.
	var block strings.Builder
	block.WriteString(serversBlockTop + "\n[servers]\n")
	names := []string{}
	for _, b := range backends {
		block.WriteString(fmt.Sprintf("%s = \"127.0.0.1:%d\"\n", b.id, b.port))
		names = append(names, fmt.Sprintf("%q", b.id))
	}
	block.WriteString("try = [" + strings.Join(names, ", ") + "]\n" + serversBlockEnd)

	tomlPath := filepath.Join(srv.DataDir(), velocityConfig)
	raw, err := os.ReadFile(tomlPath)
	if err != nil {
		return nil, fmt.Errorf("read velocity.toml: %w", err)
	}
	content := string(raw)
	start := strings.Index(content, serversBlockTop)
	end := strings.Index(content, serversBlockEnd)
	if start >= 0 && end > start {
		content = content[:start] + block.String() + content[end+len(serversBlockEnd):]
	} else {
		// The markers were edited away; append a fresh managed block.
		content = strings.TrimRight(content, "\n") + "\n\n" + block.String() + "\n"
	}
	if err := fsutil.WriteFileAtomic(tomlPath, []byte(content), 0o644); err != nil {
		return nil, err
	}

	warnings := []string{}
	for _, b := range backends {
		if err := patchPaperGlobal(b.srv.DataDir(), secret); err != nil {
			warnings = append(warnings, fmt.Sprintf("%s: paper-global.yml not updated: %v", b.id, err))
			continue
		}
		if err := m.SetProperties(b.id, map[string]string{"online-mode": "false"}); err != nil {
			warnings = append(warnings, fmt.Sprintf("%s: online-mode not updated: %v", b.id, err))
		}
	}

	srv.mu.Lock()
	ids := make([]string, 0, len(backends))
	for _, b := range backends {
		ids = append(ids, b.id)
	}
	srv.meta.NetworkServers = ids
	err = fsutil.WriteJSONAtomic(filepath.Join(srv.dir, metaFile), srv.meta)
	srv.mu.Unlock()
	if err != nil {
		return warnings, err
	}
	return warnings, nil
}

// patchPaperGlobal enables Velocity modern forwarding in a backend's
// config/paper-global.yml. Paper merges partial configs, so when the file
// does not exist yet a minimal one is written. When it exists, the three
// keys below the proxies.velocity section are rewritten in place.
func patchPaperGlobal(dataDir, secret string) error {
	cfgDir := filepath.Join(dataDir, "config")
	path := filepath.Join(cfgDir, "paper-global.yml")
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		if err := os.MkdirAll(cfgDir, 0o750); err != nil {
			return err
		}
		minimal := fmt.Sprintf("proxies:\n  velocity:\n    enabled: true\n    online-mode: true\n    secret: '%s'\n", secret)
		return fsutil.WriteFileAtomic(path, []byte(minimal), 0o644)
	}
	if err != nil {
		return err
	}

	lines := strings.Split(strings.ReplaceAll(string(raw), "\r\n", "\n"), "\n")
	inVelocity := false
	velocityIndent := 0
	patched := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		indent := len(line) - len(strings.TrimLeft(line, " "))
		if trimmed == "velocity:" {
			inVelocity = true
			velocityIndent = indent
			continue
		}
		if inVelocity {
			if trimmed != "" && indent <= velocityIndent {
				inVelocity = false
				continue
			}
			pad := strings.Repeat(" ", velocityIndent+2)
			switch {
			case strings.HasPrefix(trimmed, "enabled:"):
				lines[i] = pad + "enabled: true"
				patched = true
			case strings.HasPrefix(trimmed, "online-mode:"):
				lines[i] = pad + "online-mode: true"
			case strings.HasPrefix(trimmed, "secret:"):
				lines[i] = pad + "secret: '" + secret + "'"
			}
		}
	}
	if !patched {
		// No proxies.velocity section found, append one.
		content := strings.TrimRight(strings.Join(lines, "\n"), "\n")
		content += fmt.Sprintf("\nproxies:\n  velocity:\n    enabled: true\n    online-mode: true\n    secret: '%s'\n", secret)
		return fsutil.WriteFileAtomic(path, []byte(content), 0o644)
	}
	return fsutil.WriteFileAtomic(path, []byte(strings.Join(lines, "\n")), 0o644)
}
