package mc

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/computenord/craftpanel/internal/fsutil"
)

// A Velocity proxy and its Paper backends are wired up here: the panel owns
// the [servers] block in velocity.toml (between marker comments) and pushes
// the forwarding secret into each backend's paper-global.yml.

var ErrNotVelocity = errors.New("this server is not a velocity proxy")

const (
	velocityConfig  = "velocity.toml"
	forwardSecret   = "forwarding.secret"
	serversBlockTop = "# craftpanel:servers:start"
	serversBlockEnd = "# craftpanel:servers:end"
	forcedBlockTop  = "# craftpanel:forced-hosts:start"
	forcedBlockEnd  = "# craftpanel:forced-hosts:end"
)

// writeVelocityConfig creates the initial proxy configuration at server
// creation time.
func writeVelocityConfig(dataDir, name string, port int) error {
	secret := make([]byte, 12)
	if _, err := rand.Read(secret); err != nil {
		return err
	}
	if err := fsutil.WriteFileAtomic(filepath.Join(dataDir, forwardSecret), []byte(hex.EncodeToString(secret)), 0o600); err != nil {
		return err
	}
	toml := fmt.Sprintf(`# Generated by ComputeBox Craftpanel
config-version = "2.7"
bind = "0.0.0.0:%d"
motd = "%s"
show-max-players = 500
online-mode = true
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"

%s
[servers]
try = []
%s

%s
[forced-hosts]
%s

[advanced]
# craftpanel:proxy-protocol:start
proxy-protocol = false
# craftpanel:proxy-protocol:end
`, port, sanitizeMOTD(name), serversBlockTop, serversBlockEnd, forcedBlockTop, forcedBlockEnd)
	return fsutil.WriteFileAtomic(filepath.Join(dataDir, velocityConfig), []byte(toml), 0o644)
}

const (
	proxyProtoTop = "# craftpanel:proxy-protocol:start"
	proxyProtoEnd = "# craftpanel:proxy-protocol:end"
)

func applyVelocityProxyProtocol(dataDir string, enabled bool) error {
	path := filepath.Join(dataDir, velocityConfig)
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	block := fmt.Sprintf("%s\nproxy-protocol = %v\n%s", proxyProtoTop, enabled, proxyProtoEnd)
	content := string(raw)
	if strings.Contains(content, proxyProtoTop) {
		content = spliceBlock(content, proxyProtoTop, proxyProtoEnd, block)
	} else if idx := strings.Index(content, "[advanced]"); idx >= 0 {
		// Insert after [advanced] line.
		rest := content[idx:]
		nl := strings.Index(rest, "\n")
		if nl < 0 {
			content += "\n" + block + "\n"
		} else {
			insertAt := idx + nl + 1
			content = content[:insertAt] + block + "\n" + content[insertAt:]
		}
	} else {
		content = strings.TrimRight(content, "\n") + "\n\n[advanced]\n" + block + "\n"
	}
	return fsutil.WriteFileAtomic(path, []byte(content), 0o644)
}

func patchPaperProxyProtocol(dataDir string, enabled bool) error {
	cfgDir := filepath.Join(dataDir, "config")
	path := filepath.Join(cfgDir, "paper-global.yml")
	raw, err := os.ReadFile(path)
	val := "false"
	if enabled {
		val = "true"
	}
	if os.IsNotExist(err) {
		if err := os.MkdirAll(cfgDir, 0o750); err != nil {
			return err
		}
		minimal := fmt.Sprintf("proxies:\n  proxy-protocol: %s\n", val)
		return fsutil.WriteFileAtomic(path, []byte(minimal), 0o644)
	}
	if err != nil {
		return err
	}
	lines := strings.Split(strings.ReplaceAll(string(raw), "\r\n", "\n"), "\n")
	found := false
	inProxies := false
	proxiesIndent := 0
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		indent := len(line) - len(strings.TrimLeft(line, " "))
		if trimmed == "proxies:" {
			inProxies = true
			proxiesIndent = indent
			continue
		}
		if inProxies {
			if trimmed != "" && !strings.HasPrefix(trimmed, "#") && indent <= proxiesIndent {
				inProxies = false
			} else if strings.HasPrefix(trimmed, "proxy-protocol:") {
				lines[i] = strings.Repeat(" ", proxiesIndent+2) + "proxy-protocol: " + val
				found = true
			}
		}
	}
	if !found {
		content := strings.TrimRight(strings.Join(lines, "\n"), "\n")
		if strings.Contains(content, "proxies:") {
			content += fmt.Sprintf("\n  proxy-protocol: %s\n", val)
		} else {
			content += fmt.Sprintf("\nproxies:\n  proxy-protocol: %s\n", val)
		}
		return fsutil.WriteFileAtomic(path, []byte(content), 0o644)
	}
	return fsutil.WriteFileAtomic(path, []byte(strings.Join(lines, "\n")), 0o644)
}

func isPaperFamily(typ string) bool {
	switch typ {
	case TypePaper, TypePurpur, TypeFolia:
		return true
	default:
		return false
	}
}

// spliceBlock replaces the marker-delimited managed section of a config
// file, appending a fresh block when the markers were edited away.
func spliceBlock(content, top, end, block string) string {
	s := strings.Index(content, top)
	e := strings.Index(content, end)
	if s >= 0 && e > s {
		return content[:s] + block + content[e+len(end):]
	}
	return strings.TrimRight(content, "\n") + "\n\n" + block + "\n"
}

// forcedHostsBlock renders the managed [forced-hosts] table: players who
// connect via <backend>.<domain> land directly on that backend.
func forcedHostsBlock(domain string, backendIDs []string) string {
	var b strings.Builder
	b.WriteString(forcedBlockTop + "\n[forced-hosts]\n")
	if domain != "" {
		for _, id := range backendIDs {
			b.WriteString(fmt.Sprintf("%q = [%q]\n", id+"."+domain, id))
		}
	}
	b.WriteString(forcedBlockEnd)
	return b.String()
}

// applyForcedHosts rewrites the managed [forced-hosts] block of one proxy's
// velocity.toml. A non-empty warning means the file was left untouched.
func applyForcedHosts(dataDir, domain string, backendIDs []string) (string, error) {
	path := filepath.Join(dataDir, velocityConfig)
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	content := string(raw)
	if !strings.Contains(content, forcedBlockTop) && strings.Contains(content, "[forced-hosts]") {
		return "velocity.toml contains a hand-written [forced-hosts] section, left untouched", nil
	}
	content = spliceBlock(content, forcedBlockTop, forcedBlockEnd, forcedHostsBlock(domain, backendIDs))
	return "", fsutil.WriteFileAtomic(path, []byte(content), 0o644)
}

// rewriteAllForcedHosts refreshes the forced-hosts mapping of every proxy
// after the base domain changed. Returns human readable warnings.
func (m *Manager) rewriteAllForcedHosts(domain string) []string {
	m.mu.Lock()
	servers := make([]*Server, 0, len(m.items))
	for _, s := range m.items {
		servers = append(servers, s)
	}
	m.mu.Unlock()

	warnings := []string{}
	touched := false
	for _, srv := range servers {
		srv.mu.Lock()
		typ, id := srv.meta.Type, srv.meta.ID
		backends := append([]string{}, srv.meta.NetworkServers...)
		srv.mu.Unlock()
		if typ != TypeVelocity {
			continue
		}
		w, err := applyForcedHosts(srv.DataDir(), domain, backends)
		switch {
		case err != nil:
			warnings = append(warnings, id+": velocity.toml not updated: "+err.Error())
		case w != "":
			warnings = append(warnings, id+": "+w)
		default:
			touched = true
		}
	}
	if touched {
		warnings = append(warnings, "Restart the Velocity proxies so the new domain mapping takes effect.")
	}
	return warnings
}

type NetworkBackend struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Port   int    `json:"port"`
	Linked bool   `json:"linked"`
}

type NetworkInfo struct {
	Backends []NetworkBackend `json:"backends"`
	// Domain is the panel's base domain; linked backends are reachable at
	// <id>.<Domain> via forced hosts. DNSManaged reports whether the panel
	// also maintains SRV records, which makes the proxy port irrelevant.
	Domain        string   `json:"domain,omitempty"`
	ProxyPort     int      `json:"proxyPort"`
	DNSManaged    bool     `json:"dnsManaged"`
	ProxyProtocol bool     `json:"proxyProtocol"`
	Hints         []string `json:"hints,omitempty"`
}

// Network lists Paper-family servers on this host and whether they are wired
// to the given Velocity proxy.
func (m *Manager) Network(id string) (NetworkInfo, error) {
	srv, err := m.get(id)
	if err != nil {
		return NetworkInfo{}, err
	}
	if srv.meta.Type != TypeVelocity {
		return NetworkInfo{}, ErrNotVelocity
	}
	linked := map[string]bool{}
	srv.mu.Lock()
	proxyPort := srv.meta.Port
	proxyProto := srv.meta.ProxyProtocol
	for _, l := range srv.meta.NetworkServers {
		linked[l] = true
	}
	srv.mu.Unlock()

	st := m.Settings()
	info := NetworkInfo{
		Backends:      []NetworkBackend{},
		Domain:        st.Domain,
		ProxyPort:     proxyPort,
		DNSManaged:    dnsConfigured(st),
		ProxyProtocol: proxyProto,
		Hints:         proxyHints(proxyProto, st.Domain, proxyPort),
	}
	for _, v := range m.List() {
		if !isPaperFamily(v.Type) {
			continue
		}
		info.Backends = append(info.Backends, NetworkBackend{
			ID: v.ID, Name: v.Name, Port: v.Port, Linked: linked[v.ID],
		})
	}
	sort.Slice(info.Backends, func(i, j int) bool { return info.Backends[i].ID < info.Backends[j].ID })
	return info, nil
}

func proxyHints(proxyProtocol bool, domain string, proxyPort int) []string {
	hints := []string{
		"Put the panel behind a reverse proxy with WebSocket support for the live console (SSE).",
		"Forward X-Forwarded-Proto and (only from trusted proxies) X-Forwarded-For; run craftpanel with -behind-proxy.",
	}
	if domain != "" {
		hints = append(hints, "Players can use <server>."+domain+" when forced-hosts and DNS are configured.")
	}
	if proxyPort != 25565 && !proxyProtocol {
		hints = append(hints, fmt.Sprintf("Proxy listens on %d — players must use that port unless you have SRV records.", proxyPort))
	}
	if proxyProtocol {
		hints = append(hints, "PROXY protocol is on: your TCP load balancer must send PROXY v1/v2; direct player connects will fail.")
	} else {
		hints = append(hints, "Enable PROXY protocol only when a TCP proxy (HAProxy/Nginx stream) sits in front of Velocity.")
	}
	return hints
}

// SetNetwork wires the chosen Paper-family servers to the proxy: velocity.toml
// gets the server list, every chosen backend gets the forwarding secret and
// online-mode=false. Returns human readable warnings (restart reminders).
func (m *Manager) SetNetwork(id string, serverIDs []string, proxyProtocol *bool) ([]string, error) {
	srv, err := m.get(id)
	if err != nil {
		return nil, err
	}
	if srv.meta.Type != TypeVelocity {
		return nil, ErrNotVelocity
	}
	secretBytes, err := os.ReadFile(filepath.Join(srv.DataDir(), forwardSecret))
	if err != nil {
		return nil, fmt.Errorf("read forwarding secret: %w", err)
	}
	secret := strings.TrimSpace(string(secretBytes))

	// Validate the chosen backends first.
	type backend struct {
		id   string
		port int
		srv  *Server
	}
	backends := []backend{}
	seen := map[string]bool{}
	for _, sid := range serverIDs {
		if seen[sid] || sid == id {
			continue
		}
		seen[sid] = true
		b, err := m.get(sid)
		if err != nil {
			return nil, fmt.Errorf("server %q not found", sid)
		}
		b.mu.Lock()
		typ, port := b.meta.Type, b.meta.Port
		b.mu.Unlock()
		if !isPaperFamily(typ) {
			return nil, fmt.Errorf("server %q is not a Paper/Purpur/Folia server", sid)
		}
		backends = append(backends, backend{id: sid, port: port, srv: b})
	}

	// Rebuild the managed [servers] block in velocity.toml.
	var block strings.Builder
	block.WriteString(serversBlockTop + "\n[servers]\n")
	names := []string{}
	for _, b := range backends {
		block.WriteString(fmt.Sprintf("%s = \"127.0.0.1:%d\"\n", b.id, b.port))
		names = append(names, fmt.Sprintf("%q", b.id))
	}
	block.WriteString("try = [" + strings.Join(names, ", ") + "]\n" + serversBlockEnd)

	tomlPath := filepath.Join(srv.DataDir(), velocityConfig)
	raw, err := os.ReadFile(tomlPath)
	if err != nil {
		return nil, fmt.Errorf("read velocity.toml: %w", err)
	}
	content := spliceBlock(string(raw), serversBlockTop, serversBlockEnd, block.String())
	if err := fsutil.WriteFileAtomic(tomlPath, []byte(content), 0o644); err != nil {
		return nil, err
	}

	warnings := []string{}

	// Keep the domain mapping in step: every linked backend gets a forced
	// host <id>.<domain> so players land on the right server by hostname.
	backendIDs := make([]string, 0, len(backends))
	for _, b := range backends {
		backendIDs = append(backendIDs, b.id)
	}
	if w, err := applyForcedHosts(srv.DataDir(), m.Settings().Domain, backendIDs); err != nil {
		warnings = append(warnings, "forced hosts not updated: "+err.Error())
	} else if w != "" {
		warnings = append(warnings, w)
	}
	for _, b := range backends {
		if err := patchPaperGlobal(b.srv.DataDir(), secret); err != nil {
			warnings = append(warnings, fmt.Sprintf("%s: paper-global.yml not updated: %v", b.id, err))
			continue
		}
		if err := m.SetProperties(b.id, map[string]string{"online-mode": "false"}); err != nil {
			warnings = append(warnings, fmt.Sprintf("%s: online-mode not updated: %v", b.id, err))
		}
	}

	srv.mu.Lock()
	srv.meta.NetworkServers = backendIDs
	if proxyProtocol != nil {
		srv.meta.ProxyProtocol = *proxyProtocol
	}
	proxyOn := srv.meta.ProxyProtocol
	err = fsutil.WriteJSONAtomic(filepath.Join(srv.dir, metaFile), srv.meta)
	srv.mu.Unlock()
	if err != nil {
		return warnings, err
	}
	if err := applyVelocityProxyProtocol(srv.DataDir(), proxyOn); err != nil {
		warnings = append(warnings, "velocity proxy-protocol not updated: "+err.Error())
	}
	for _, b := range backends {
		if err := patchPaperProxyProtocol(b.srv.DataDir(), proxyOn); err != nil {
			warnings = append(warnings, fmt.Sprintf("%s: proxy-protocol not updated: %v", b.id, err))
		}
	}
	// Proxy membership changes which port the backends' SRV records point at.
	m.TriggerDNSSync("network changed")
	return warnings, nil
}

// patchPaperGlobal enables Velocity modern forwarding in a backend's
// config/paper-global.yml. Paper merges partial configs, so when the file
// does not exist yet a minimal one is written. When it exists, the three
// keys below the proxies.velocity section are rewritten in place.
func patchPaperGlobal(dataDir, secret string) error {
	cfgDir := filepath.Join(dataDir, "config")
	path := filepath.Join(cfgDir, "paper-global.yml")
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		if err := os.MkdirAll(cfgDir, 0o750); err != nil {
			return err
		}
		minimal := fmt.Sprintf("proxies:\n  velocity:\n    enabled: true\n    online-mode: true\n    secret: '%s'\n", secret)
		return fsutil.WriteFileAtomic(path, []byte(minimal), 0o644)
	}
	if err != nil {
		return err
	}

	lines := strings.Split(strings.ReplaceAll(string(raw), "\r\n", "\n"), "\n")
	inVelocity := false
	velocityIndent := 0
	patched := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		indent := len(line) - len(strings.TrimLeft(line, " "))
		if trimmed == "velocity:" {
			inVelocity = true
			velocityIndent = indent
			continue
		}
		if inVelocity {
			if trimmed != "" && indent <= velocityIndent {
				inVelocity = false
				continue
			}
			pad := strings.Repeat(" ", velocityIndent+2)
			switch {
			case strings.HasPrefix(trimmed, "enabled:"):
				lines[i] = pad + "enabled: true"
				patched = true
			case strings.HasPrefix(trimmed, "online-mode:"):
				lines[i] = pad + "online-mode: true"
			case strings.HasPrefix(trimmed, "secret:"):
				lines[i] = pad + "secret: '" + secret + "'"
			}
		}
	}
	if !patched {
		// No proxies.velocity section found, append one.
		content := strings.TrimRight(strings.Join(lines, "\n"), "\n")
		content += fmt.Sprintf("\nproxies:\n  velocity:\n    enabled: true\n    online-mode: true\n    secret: '%s'\n", secret)
		return fsutil.WriteFileAtomic(path, []byte(content), 0o644)
	}
	return fsutil.WriteFileAtomic(path, []byte(strings.Join(lines, "\n")), 0o644)
}
