// Downloads the UI fonts (latin subsets) from Google Fonts and writes
// internal/web/static/fonts.css plus the woff2 files, so the panel binary is
// fully self-contained and works offline. Run once before building:
//   node scripts/fetch-fonts.mjs
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const staticDir = join(root, "internal", "web", "static");
const fontsDir = join(staticDir, "fonts");

const FAMILIES = [
  { family: "Chakra Petch", css: "Chakra+Petch", weights: [600, 700] },
  { family: "IBM Plex Sans", css: "IBM+Plex+Sans", weights: [400, 500, 600] },
  { family: "JetBrains Mono", css: "JetBrains+Mono", weights: [400, 700] },
];

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

async function latinFace(cssFamily, weight) {
  const url = `https://fonts.googleapis.com/css2?family=${cssFamily}:wght@${weight}&display=swap`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${url}: ${res.status}`);
  const css = await res.text();
  // Faces are grouped by subset comments; take the block following /* latin */.
  const blocks = css.split("/*").filter((b) => b.trim().startsWith("latin */"));
  const block = blocks[blocks.length - 1];
  if (!block) throw new Error(`no latin subset for ${cssFamily} ${weight}`);
  const m = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/);
  if (!m) throw new Error(`no woff2 url for ${cssFamily} ${weight}`);
  return m[1];
}

await mkdir(fontsDir, { recursive: true });
let css = "/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n";
for (const f of FAMILIES) {
  for (const w of f.weights) {
    const url = await latinFace(f.css, w);
    const file = `${f.css.replaceAll("+", "").toLowerCase()}-${w}.woff2`;
    const bin = await fetch(url, { headers: { "User-Agent": UA } });
    if (!bin.ok) throw new Error(`${url}: ${bin.status}`);
    await writeFile(join(fontsDir, file), Buffer.from(await bin.arrayBuffer()));
    css += `@font-face{font-family:"${f.family}";font-style:normal;font-weight:${w};font-display:swap;src:url(/assets/fonts/${file}) format("woff2");}\n`;
    console.log(`fetched ${f.family} ${w}`);
  }
}
await writeFile(join(staticDir, "fonts.css"), css);
console.log("wrote fonts.css");
